config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'shop/grid'

  get 'shop/basket'

  get 'onboardings/index'
  get 'welcome/index'

  devise_for :sellers
  devise_for :users
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/onboardings_controller.rb
class OnboardingsController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:distance, :profile_pic, :owner_name, :description, :buy_button, :price_theoric, :price_corrected, :impact)
    end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def grid
  end

  def basket 
    @products = Product.all
  end
  
  def show
  end

  def buy
     @distance = ((current_user.address_gps).distance_to(@product.seller.address_gps) * 1.6) 
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/onboardings_helper.rb
module OnboardingsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organicoin</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!-- CDN FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/grayscale.css" rel="stylesheet">
    <!-- Custom styles -->
    <link href="/assets/grid.css" rel="stylesheet">
    <!-- Custom styles -->
    <link href="/assets/products.css" rel="stylesheet">
    <!-- Web3 CDN -->
    <script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js/dist/web3.min.js"></script>
  </head>

  <body style="background-color:#73a587; color:#333">
    <%= yield %>
  </body>
</html>

app/views/onboardings/index.html.erb
<h1>Onboardings#index</h1>
<p>A quoi sert l'app</p>
<p>Find me in app/views/onboardings/index.html.erb</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :distance %>
    <%= form.text_area :distance, id: :product_distance %>
  </div>

  <div class="field">
    <%= form.label :profile_pic %>
    <%= form.text_area :profile_pic, id: :product_profile_pic %>
  </div>

  <div class="field">
    <%= form.label :owner_name %>
    <%= form.text_area :owner_name, id: :product_owner_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :buy_button %>
    <%= form.text_area :buy_button, id: :product_buy_button %>
  </div>

  <div class="field">
    <%= form.label :price_theoric %>
    <%= form.text_area :price_theoric, id: :product_price_theoric %>
  </div>

  <div class="field">
    <%= form.label :price_corrected %>
    <%= form.text_area :price_corrected, id: :product_price_corrected %>
  </div>

  <div class="field">
    <%= form.label :impact %>
    <%= form.text_area :impact, id: :product_impact %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carrots</h1>


 <!-- HERE COMES MY GRID LINE TO REPEAT -->
<% @products.each do |product| %>
  <div class="gd-container">
    <div class="item perso">
      <div class="sub-item">
        <%= image_tag product.profile_pic %>
      </div>
      <div class="sub-item">
        <p class="name"><%= product.owner_name %> <span class="distance"><i class="fas fa-map-marker-alt"></i> <%= product.distance %></span></p>
        <p><%= product.description %></p>
      </div>
    </div>
    <div class="item buy">
        <a href="" data-toggle="modal" data-target="#myModal">
            <i class="fas fa-shopping-basket fit-sz"></i>
        </a>
    </div>
    <div class="item big-price"><%= product.price_corrected %></div> 
    <div class="item price"><%= product.price_theoric %></div>
    <div class="item"><i class="fas fa-road"></i> <%= product.impact %></div>
  </div>
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
  <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <%= image_tag product.profile_pic %>
          <h4 class="modal-title"><%= product.owner_name %> is about
            <br>to thank you warmly !
          </h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body text-center">
          <p><em>Expected price in a supermarket :</em></p>
            <div class="progress">
              <div class="progress-bar bg-success progress-bar-striped progress-bar-animated" role="progressbar" style="width: 22%" aria-valuenow="22" aria-valuemin="0" aria-valuemax="100">Producer</div>
              <div class="progress-bar bg-secondary" role="progressbar" style="width: 36%" aria-valuenow="36" aria-valuemin="0" aria-valuemax="100">Distribtion</div>
              <div class="progress-bar bg-info " role="progressbar" style="width: 29%" aria-valuenow="29" aria-valuemin="0" aria-valuemax="100">Retailer</div>
              <div class="progress-bar bg-danger " role="progressbar" style="width: 13%" aria-valuenow="13" aria-valuemin="0" aria-valuemax="100">Taxes</div>
            </div>
          <p><strong>ORGANICOIN PRICE :</strong></p>
            <div class="progress">
              <div class="progress-bar bg-success progress-bar-striped progress-bar-animated" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Producer</div>
            </div>
          <p>
            <i class="fas fa-leaf"></i> 416 CO2 kilograms saved !
          </p>
          <p>
            <i class="fas fa-money-bill-alt"></i> 0.01 ETH = 0.00324 OGC Tokens = 2.80 €.
          </p>
          <p>You <strong>actively</strong> participate to the environemental impact.</p>
        </div>
        <div class="modal-footer text-center" style="justify-content: center;">
          <button type="button" class="btn btn-success btn-lg" data-dismiss="modal">Confirm</button>
        </div>
      </div>
    </div>
  </div>
<% end %>


<!-- END OF THE GRID LINE -->
<br>

<%= link_to 'New Product', new_product_path %>
<a href="products/1/edit" style="color:rgb(115, 165, 135)">P1</a>
<a href="products/2/edit" style="color:rgb(115, 165, 135)">P2</a>
<a href="products/3/edit" style="color:rgb(115, 165, 135)">P3</a>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Distance:</strong>
  <%= @product.distance %>
</p>

<p>
  <strong>Profile pic:</strong>
  <%= image_tag @product.profile_pic, size: "160x160" %>
</p>

<p>
  <strong>Owner name:</strong>
  <%= @product.owner_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Buy button:</strong>
  <%= @product.buy_button %>
</p>

<p>
  <strong>Price theoric:</strong>
  <%= @product.price_theoric %>
</p>

<p>
  <strong>Price corrected:</strong>
  <%= @product.price_corrected %>
</p>

<p>
  <strong>Impact:</strong>
  <%= @product.impact %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shop/basket.html.erb
<% @products.each do |p| %>
    <%= p.name %>
    <%= p.price %>
    <%= p.qty %>
    <%= link_to 'Show', p %>
<% end %>

app/views/shop/grid.html.erb
<div class="item-wraper">
	<div class="card" style="width: 18rem;">
		<%= link_to products_path do %>
		  	<img class="card-img-top" src="http://selection.readersdigest.ca/wp-content/uploads/2016/06/vertus_carottes.jpg" alt="Card image cap">
		  	<div class="card-body">          
	      		<h5 class="card-title">Carrots</h5>
	  		</div>
	  	<% end %>
  </div>
  

  <div class="card" style="width: 18rem;">
  	<%= link_to products_path do %>
		<img class="card-img-top" src="http://cache.marieclaire.fr/data/photo/w1000_c17/i14a/149022506.jpg">
		<div class="card-body">
			<h5 class="card-title">Turnips</h5>
  		</div>
  	<% end %>
  </div>
  <div class="card" style="width: 18rem;">
  	<%= link_to products_path do %>
	  <img class="card-img-top" src="http://www.grupocatala.com/images/fondos/tomate.jpg" alt="Card image cap">
	  <div class="card-body">
      <h5 class="card-title">Tomatoes</h5>
  	</div>
  	<% end %>
  </div>
  <div class="card" style="width: 18rem;">
  	<%= link_to products_path do %>
	  	<img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Pommes_de_terre_Monalisa.png/1200px-Pommes_de_terre_Monalisa.png" alt="Card image cap">
	  	<div class="card-body">
      		<h5 class="card-title">Potatoes</h5>
  		</div>
  	<% end %>
  </div>
  <div class="card" style="width: 18rem;">
  	<%= link_to products_path do %>
	  <img class="card-img-top" src="http://selection.readersdigest.ca/wp-content/uploads/2016/06/aubergine_legume_decouvrir.jpg" alt="Card image cap">
	  	<div class="card-body">
      		<h5 class="card-title">Eggplants</h5>
  		</div>
  	<% end %>
  </div>
  <div class="card" style="width: 18rem;">
  	<%= link_to products_path do %>
	  <img class="card-img-top" src="http://www.marecettesante.com/blog/wp-content/uploads/2015/06/celeri-rave-defi-legumes-21-jours-recette-sante.jpg" alt="Card image cap">
		<div class="card-body">
	    	<h5 class="card-title">Celery</h5>
  		</div>
  	<% end %>
  </div>
  <div class="card" style="width: 18rem;">
  	<%= link_to products_path do %>
	  <img class="card-img-top" src="https://i.skyrock.net/2501/91542501/pics/3254523796_1_3_o9eBe9qy.jpg" alt="Card image cap">
	  <div class="card-body">
      <h5 class="card-title">Green Beans</h5>
  	</div>
  <% end %>
  </div>
  <div class="card" style="width: 18rem;">
  	<%= link_to products_path do %>
	  <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjEGJQNeIjaYJo3ajAhhqQZOdquhX3KZwik_BCV9yRbcITcuC8Cw" alt="Card image cap">
	  <div class="card-body">
      <h5 class="card-title">Apples</h5>
  	</div>
  <% end %>
  </div>

</div>

app/views/welcome/index.html.erb
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
</head>

<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">Organicoin</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#go">Buy Food</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Intro Header -->
    <header class="masthead">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h1 class="brand-heading">Organicoin</h1>
                        <p class="intro-text">We disrupt the food industry by connecting local food-growers with customers.</p>
                        <a href="#go" class="btn btn-circle js-scroll-trigger">
                <i class="fa fa-angle-double-down animated"></i>
              </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- ########################### -->
    <section style="background-color: white;color: #333;text-align: center;padding: 3em;">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                        <div class="features-icons-icon d-flex">
                            <i class="icon-screen-desktop m-auto text-primary"></i>
                        </div>
                        <h3>Transparency by design</h3>
                        <p><i class="fas fa-eye fa-3x"></i></p>
                        <p class="lead mb-0">By using the latest blockchain technology, we ensure absolute user control and transaction transparency.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                        <div class="features-icons-icon d-flex">
                            <i class="icon-layers m-auto text-primary"></i>
                        </div>
                        <h3>Fairest</br>prices</h3>
                        <p><i class="fas fa-balance-scale fa-3x"></i></p>
                        <p class="lead mb-0">We cut off expensive and toxic middlemen to allow for better pricing and quality.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="features-icons-item mx-auto mb-0 mb-lg-3">
                        <div class="features-icons-icon d-flex">
                            <i class="icon-check m-auto text-primary"></i>
                        </div>
                        <h3>Environmental</br>& social impact</h3>
                        <p><i class="fas fa-leaf fa-3x"></i></p>
                        <p class="lead mb-0">We are environmentally and socially engaged: making a positive impact, while still being advantageous for the customer.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- CTA -->
    <section id="go" class="text-center" style="padding: 6em;background-color: white;">
        <div class="container">
            <div class="row">
              <div class="col-12 ">
        <!-- <button type="button" >Make an impact</button> -->
        <%= link_to 'Make an impact', shop_grid_path , :class => 'btn btn-primary btn-lg'%>
              </div> 
            </div>
        </div>
    </section>
    <!-- About Section -->
    <!-- <section id="about" class="content-section text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>About Grayscale</h2>
                    <p>Grayscale is a free Bootstrap theme created by Start Bootstrap. It can be yours right now, simply download the template on
                        <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.</p>
                    <p>This theme features stock photos by
                        <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Maps skin courtesy of
                        <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
                    <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with SASS and LESS files for easy customization!</p>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col">
                    Bonjour
                </div>
                <div class="col">
                    Le monde
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    Hello
                </div>
                <div class="col-lg-4">
                    World
                </div>
                <div class="col-lg-4">
                    Lol !!
                </div>
            </div>
        </div>
    </section> -->

    <!-- Download Section -->
     <!-- <section id="download" class="download-section content-section text-center">
      <div class="container">
        <div class="col-lg-8 mx-auto">
          <h2>Download Grayscale</h2>
          <p>You can download Grayscale for free on the preview page at Start Bootstrap.</p>
          <a href="http://startbootstrap.com/template-overviews/grayscale/" class="btn btn-default btn-lg">Visit Download Page</a>
        </div>
      </div>
    </section> -->
    <!-- Contact Section -->
    <!-- <section id="contact" class="content-section text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>Contact Start Bootstrap</h2>
                    <p>Feel free to leave us a comment on the
                        <a href="http://startbootstrap.com/template-overviews/grayscale/">Grayscale template overview page</a> on Start Bootstrap to give some feedback about this theme!</p>
                    <ul class="list-inline banner-social-buttons">
                        <li class="list-inline-item">
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg">
                  <i class="fa fa-twitter fa-fw"></i>
                  <span class="network-name">Twitter</span>
                </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/BlackrockDigital/startbootstrap" class="btn btn-default btn-lg">
                  <i class="fa fa-github fa-fw"></i>
                  <span class="network-name">Github</span>
                </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg">
                  <i class="fa fa-google-plus fa-fw"></i>
                  <span class="network-name">Google+</span>
                </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section> -->
    
    <!-- Map Section -->
    <!-- <div id="map"></div> -->
    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Made with <i class="fas fa-heart"></i> during the AngelHack Hackathon 2018</p>
        </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script> -->
    <!-- Custom scripts for this template -->
    <script src="grayscale.min.js"></script>